#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime
import sys


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "repo-map.md"
ALLOWED_EXTENSIONS = {".md", ".py", ".sh", ".json", ".yml", ".yaml"}
EXCLUDED_DIRS = {
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    "node_modules",
    "dist",
    "build",
    ".cache",
    ".pytest_cache",
    ".mypy_cache",
}
EXCLUDED_FILES = {"repo-map.md", ".DS_Store"}
TYPE_MAP = {
    ".md": "markdown",
    ".py": "python",
    ".sh": "shell",
    ".json": "json",
    ".yml": "yaml",
    ".yaml": "yaml",
}


def should_skip(path):
    relative = path.relative_to(ROOT)
    for part in relative.parts:
        if part in EXCLUDED_DIRS:
            return True
    if relative.name in EXCLUDED_FILES:
        return True
    return False


def collect_headings(path):
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return [], True

    headings = []
    in_code_block = False

    for line in text.splitlines():
        if line.startswith("```"):
            in_code_block = not in_code_block
            continue
        if in_code_block:
            continue

        stripped = line.lstrip()
        if stripped.startswith("### "):
            heading = stripped[4:].strip()
        elif stripped.startswith("## "):
            heading = stripped[3:].strip()
        elif stripped.startswith("# "):
            heading = stripped[2:].strip()
        else:
            continue

        if heading:
            headings.append(heading)
        if len(headings) >= 20:
            break

    return headings, False


def main():
    try:
        files = []
        counts = {
            "markdown": 0,
            "python": 0,
            "shell": 0,
            "json": 0,
            "yaml": 0,
        }

        for path in sorted(ROOT.rglob("*")):
            if not path.is_file():
                continue
            if should_skip(path):
                continue
            if path.suffix not in ALLOWED_EXTENSIONS:
                continue

            relative = path.relative_to(ROOT).as_posix()
            file_type = TYPE_MAP[path.suffix]
            size_bytes = path.stat().st_size
            headings = []
            read_error = False

            if path.suffix == ".md":
                headings, read_error = collect_headings(path)

            counts[file_type] += 1
            files.append(
                {
                    "path": relative,
                    "type": file_type,
                    "size_bytes": size_bytes,
                    "headings": headings,
                    "read_error": read_error,
                }
            )

        lines = [
            "# AgentOS Repo Map",
            "Generated by: scripts/generate-repo-map.py",
            f"Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "## Summary",
            f"- Total files: {len(files)}",
            f"- Markdown files: {counts['markdown']}",
            f"- Python files: {counts['python']}",
            f"- Shell files: {counts['shell']}",
            f"- JSON files: {counts['json']}",
            f"- YAML files: {counts['yaml']}",
            "## Files",
        ]

        for item in files:
            lines.append(f"### {item['path']}")
            lines.append(f"- type: {item['type']}")
            lines.append(f"- size_bytes: {item['size_bytes']}")
            if item["headings"]:
                lines.append("- headings:")
                for heading in item["headings"]:
                    lines.append(f"  - {heading}")
            else:
                lines.append("- headings: []")
            if item["read_error"]:
                lines.append("- read_error: true")

        OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print("PASS: repo map generated")
        return 0
    except Exception as error:
        print("FAIL: repo map generation failed")
        print(str(error))
        return 1


if __name__ == "__main__":
    sys.exit(main())
